### ISSUE TITLE
Usage with redux-thunk

### ISSUE THREAD

**Issue by robertying** [thebrodmann/deox#32] opened 2019-04-04 09:27 UTC
Hi! Thanks for this awesome library!

I'm new to Redux and had successfully done some work with `redux-thunk` in simple action creators.

However, the `resolve` in `createAction` confuses me. Is it the same `resolve` as in `Promise`, which makes me wonder if I can use async functions in `executor`?

Could you please make an example of how it works with `redux-thunk` or other async action creators?

Thank you!

**Comment by thebrodmann** [comment] 2019-04-04 11:13
Duplicate of #17

**Comment by thebrodmann** [comment] 2019-04-04 11:19
I will close the issue for housekeeping purposes. if there is something unclear, feel free to re-open the issue.

**Closed by thebrodmann** 2019-04-04 11:19 UTC
Labels: duplicate, question
